# Generated by Django 5.1 on 2024-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound',
            old_name='product',
            new_name='product_sku',
        ),
        migrations.RenameField(
            model_name='outbound',
            old_name='product',
            new_name='product_sku',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_sku',
            field=models.CharField(default='DEFAULT-SKU', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
