# Generated by Django 5.1 on 2024-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_product_inbound_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='reference',
            field=models.CharField(default='INBOUND000', max_length=10),
        ),
        migrations.AddField(
            model_name='inbound',
            name='remarks',
            field=models.CharField(default='Operator Remarks', max_length=255),
        ),
        migrations.AddField(
            model_name='outbound',
            name='reference',
            field=models.CharField(default='OUTBOUND000', max_length=10),
        ),
        migrations.AddField(
            model_name='outbound',
            name='remarks',
            field=models.CharField(default='Operator Remarks', max_length=255),
        ),
    ]
