# Generated by Django 5.1 on 2024-09-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_inventory_options_remove_inventory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('A', 'Storage A'), ('B', 'Storage B'), ('C', 'Storage C'), ('D', 'Storage D')], default='A', max_length=1),
        ),
    ]
