# Generated by Django 5.1 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_inventory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='tags',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing')], default='Electronic', max_length=50),
        ),
    ]
