# Generated by Django 5.1 on 2024-09-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_rename_tags_inventory_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbound',
            old_name='customer',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='supplier',
        ),
    ]
